algoritmo "Media"
var
   M, N1, N2, N3, N4: Real
inicio
      Escreval("-------------------------------")
      Escreval("   CALCULA MÉDIA DAS NOTAS")
      Escreval("-------------------------------")
      N1 <- 5
      N2 <- 7
      N3 <- 10
      N4 <- 3
      EscrevaL("1ª Nota: ",N1)
      EscrevaL("2ª Nota: ",N2)
      EscrevaL("3ª Nota: ",N3)
      EscrevaL("4ª Nota: ",N4)
      EscrevaL()
      M <- (N1+N2+N3+N4)/4
      EscrevaL("A média é : ",M)
fimalgoritmo